### PR TITLE
Make byLine handle carriage newline and just newline equally.

### PR DESCRIPTION
**Pull request by abersnaze**
based on a discussion on #30.

### CODE REVIEW

**Comment by Crystark** [comment]
You may want to handle \r only too as if I remember correctly, Mac OS 9 has only \r as a new line separator.

**Comment by abersnaze** [comment]
I don't know if I even want to think about what it would take to support running RxJava on what ever version of the JDK on OS 9.

I'll think about regex though.

**Comment by Crystark** [comment]
I'm not supposing it would run on OS 9 just that a file may be originating from there (for instance, reading a client's file who runs on an old OS 9)

**Comment by abersnaze** [comment]
@Crystark I got all three line ending forms able to coexist in one regex.  If you could give a :+1: I'll merge it.

**Comment by Crystark** [comment]
It seems OK to me. Although I would write the pattern like that: 
`"(\\r\\n)|(\\n)|(\\r)"` (or `"\\r?\\n|\\r"`).
If you do not double the anti-slashes, you're actually putting the the real CR and LF characters in the string instead of using the regexp constructs `\r` and `\n`. I'm really not sure what are the implications of using one or the other. It may just be fine.

Thanks alot.

**Comment by abersnaze** [comment]
@Crystark made additional changes to the regex to include all of the line terminating characters as listed in [java.util.Pattern](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#lt)

**Comment by Crystark** [comment]
:+1:

**Pull request merged**
