### PR TITLE
Documentation example of split doesn't work

### PR DESCRIPTION
**Pull request by jake-lively**
I wasn't super sure I was following your test functions so I just tested the observables by transforming them to and from arrays.

Part of the problem is StringObservable.split() seems to always behave like String.split() limit 0 which trims excess empty strings at the end. There also doesn't seem to be a way to change the limit so at least the documentation needs to be updated to show this behavior.

Changing the limit in testSplit() doesn't help which is why I went with the array tests.
Limit -1 or even something like 6 should preserve the empty strings if you follow the normal String.split().
But that limit could be for something else. I didn't dive that deep in the test code.

### CODE REVIEW

**Comment by davidmoten** [comment]
Thanks for this and excuse the delay. I'll run some examples with this myself but it certainly does appear that their is a conflict of intent in the operator that you have probably sorted out. I'll get back to you next week as I'm on holiday. Cheers.

**Comment by jake-lively** [comment]
Did this ever get resolved one way or the other? I guess I should have made an issue for it.

**Comment by akarnokd** [comment]
#47 has a fresh implementation.

**Pull request closed without merging**
