### PR TITLE
configuration to get travis to publish to bintray and sonatype.

### PR DESCRIPTION
**Pull request by abersnaze**

### CODE REVIEW

**Comment by akarnokd** [comment]
I agree with this change but want to ask: does the two-like rule apply only to the main RxJava project only?

**Comment by abersnaze** [comment]
I looked through the commit again (on my phone) and I'm not seeing the "two like rule". Could you help me out.

**Comment by akarnokd** [comment]
https://github.com/ReactiveX/RxJava/issues/3157

**Comment by abersnaze** [comment]
This sort of change is exempt from that because it's just build stuff that doesn't change the APIs.  I would have committed directly to the 1.x branch but I wanted to test the travis configuration worked PRs.

**Pull request merged**
